---
title: Bruke nøkkel:verdi-par i Python
hero_image: images/banner.png
description: Python ordbøker og nøkkel:verdi-par
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Bruke nøkkel:verdi-par i Python
