---
title: Pythonでkey:valueのペアを使う
hero_image: images/banner.png
description: Pythonのディクショナリー(辞書)とキー:値のペア
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Pythonでキー:値のペアを使う
