---
title: Usando pares chave:valor em Python
hero_image: images/banner.png
description: Dicionários Python e pares chave:valor
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Usando pares chave:valor em Python
