---
title: Korištenje ključ:vrijednost parova u Pythonu
hero_image: images/banner.png
description: Rječnici u Pythonu i ključ:vrijednost parovi
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Korištenje ključ:vrijednost parova u Pythonu
