---
title: Using key:value pairs in Python
hero_image: images/banner.png
description: Python dictionaries and key:value pairs
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Using key:value pairs in Python
