---
title: Usando os pares chave-valor em Python
hero_image: images/banner.png
description: Dicionários do Python e pares chave-valor
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Usando os pares chave-valor em Python
