---
title: Usando pares clave:valor en Python
hero_image: images/banner.png
description: Diccionarios Python y pares clave:valor
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - title: Usando pares clave:valor en Python
