---
title: Utilisation de paires clé-valeur en Python
hero_image: images/banner.png
description: Dictionnaires Python et paires clé-valeur
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Utilisation de paires clé-valeur en Python
