---
title: 'Python හි යතුරු:අගය(key : Value) යුගල(pairs) භාවිතා කිරීම'
hero_image: images / banner.png
description: Python ශබ්දකෝෂ(dictionaries) සහ යතුර:අගය(key:value) යුගල(pairs)
original_url:
theme: cc-ප්‍රදර්ශකය
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: 'Python හි යතුරු:අගය(key : Value) යුගල(pairs) භාවිතා කිරීම'
