---
title: Python'da, anahtar:değer ( key:value ) eşlerini kullanma
hero_image: images/banner.png
description: Python sözlükleri ve anahtar:değer (key:value) eşleri
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - 
    title: Python'da, anahtar:değer ( key:value ) eşlerini kullanma
